// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC28wzRzacMBLrdmcfHemJ40FvF6IT_H8A',
    appId: '1:670242110053:web:3b5802cb4ab68f366fa48c',
    messagingSenderId: '670242110053',
    projectId: 'chatapp-demo-ug',
    authDomain: 'chatapp-demo-ug.firebaseapp.com',
    storageBucket: 'chatapp-demo-ug.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02YJetIb5n3t7X8rMwFJiDGS07FyU_9g',
    appId: '1:670242110053:android:7ef2632b915c55876fa48c',
    messagingSenderId: '670242110053',
    projectId: 'chatapp-demo-ug',
    storageBucket: 'chatapp-demo-ug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsD2p_lbcKjHLBEnPs1AE0xWUU_F6V0-U',
    appId: '1:670242110053:ios:b8055ffc76f601c66fa48c',
    messagingSenderId: '670242110053',
    projectId: 'chatapp-demo-ug',
    storageBucket: 'chatapp-demo-ug.firebasestorage.app',
    iosBundleId: 'com.example.chatappDemoUg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsD2p_lbcKjHLBEnPs1AE0xWUU_F6V0-U',
    appId: '1:670242110053:ios:a95a4ae0f1183a936fa48c',
    messagingSenderId: '670242110053',
    projectId: 'chatapp-demo-ug',
    storageBucket: 'chatapp-demo-ug.firebasestorage.app',
    iosBundleId: 'com.example.chatappDemoUg.RunnerTests',
  );
}
